#!/bin/bash
releasev_goto_filepath=~/'.bash_ccm/goto.sh'
if [ -f $releasev_goto_filepath ]
then
	cp $releasev_goto_filepath .
else
	echo "Can't find goto.sh at path '$releasev_goto_filepath'"
	return 1
fi
# Correct some idiosyncrasies for general release.
sed -i '' 's@^gotov_dest_dirpath=~/".bash_ccm"\(.*\)$@gotov_dest_dirpath=~/".goto"\1@' goto.sh
sed -i '' 's@^\(gotov_alias_filepath=.*# uncomment.*\)$@# \1@' goto.sh
sed -i '' 's@^# \(gotov_alias_filepath=.*# comment.*\)$@\1@' goto.sh
# Change first time back to true.
sed -i '' 's@^# FIRSTTIME=FALSE$@# FIRSTTIME=TRUE@' goto.sh
# Update build metadata in the semver variable
build_metadata=$( date '+%Y%m%d%H%M%S' )
build_metadata_sed_string='s@^\(gotov_semver=\"v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*-[a|b]\.[0-9][0-9]*+\).*$@\1'
build_metadata_sed_string+="${build_metadata}"
build_metadata_sed_string+='"@'
sed -i '' "${build_metadata_sed_string}" goto.sh
awk -F'=' '/gotov_semver=/ { semver=$2; gsub(/"/,"",semver); print semver }' goto.sh 
awk -F'=' '/gotov_semver=/ { semver=$2; gsub(/"/,"",semver); sub(/-.*$/,"",semver); print semver }' goto.sh > semver
